### ISSUE TITLE
Max rating

### ISSUE THREAD

**Issue by negamartin** [IIC2133-PUC/2022-2#11]
Hola!

Tengo dos dudas sobre el `MAX RATING` en el comando `IMPRIMIR-DISCO`:

1. En caso de empate en rating, se usa el primer máximo o el último máximo?
2. El formato de output es `MAX RATING songID`. Un ejemplo concreto sería `MAX RATING 2` o `MAX 5 2`? En otras palabras, se reemplaza `RATING` por el valor numérico del rating?

Tengo las mismas dudas respecto al `MIN RATING`, pero asumo que la respuesta va para ambas.

**Comment by etoteiza** [comment]
Hola!

1-  En caso de empate, se usa el primer máximo encontrado 

2- El formato del output sería más bien `MAX_RATING songID`, es decir, un ejemplo sería `5 2` (lo vamos a aclarar de manera general pronto en el enunciado)

Lo mismo para el mínimo.
