### ISSUE TITLE
¿Cómo puedo ver que funciona mi código?

### ISSUE THREAD

**Issue by nolate26** [IIC2133-PUC/2022-2#14]
Hola! estaba comenzando mi tarea y no entiendo muy bien como puedo ver si es que se están incorporando correctamente los valores del input a mis structs. Como puedo verlo? 
De antemano muchas gracias!

**Comment by fddelabarra** [comment]
Puedes hacerlo como en Python, dándole inputs de ejemplo e imprimiéndolas con la función ‘’’printf()’’’

**Comment by nolate26** [comment]
Sisi,  entiendo pero como debo mandar los inputs según el código de inputs que hicieron?

**Comment by nolate26** [comment]
Que cree un .txt y pero no me asigna los datos de rating y length

**Comment by fddelabarra** [comment]
Colocaste las funciones que crearan las estructuras en el main.c? Y leíste el archivo correctamente?

**Comment by fddelabarra** [comment]
Te recomiendo buscar ayuda en discord, así pueden guiarte por voz

**Comment by nolate26** [comment]
Lo arregle! gracias!
