### ISSUE TITLE
Llegada de inputs

### ISSUE THREAD

**Issue by vicente999** [IIC2133-PUC/2022-2#15]
Holaa una duda...en el input primero se van a instanciar todos los discos con sus canciones antes que las playlist o se puede llamar a una playlist antes de que se instancie un disco?
ej:
1
2
CREAR-DISCO 4
20 3
50 5
35 2
60 20
CREAR-BATIPLAYLIST 0
AGREGAR-CANCION-BATIPLAYLIST 0 0 3
CREAR-DISCO 2
66 26
50 5
AGREGAR-CANCION-BATIPLAYLIST 0 1 1
FIN

**Comment by hebusch** [comment]
Hola @vicente999, primero se van a instancias todos los discos.
