### ISSUE TITLE
T0: Tests

### ISSUE THREAD

**Issue by siescobedo** [IIC2133-PUC/2022-2#17]
Hola, 

En el anuncio de Uso de Servidor dice que los tests están disponibles en el Siding, pero cuando intento entrar no me dejaba ver mis ramos del 2022-2 y cuando al fin logré entrar "a la mala" (cambiando el link para que fuera 2022-2), no hay hipervínculo al ramo. ¿Sería posible que suban los tests en algún otro lado? Me gustaría revisarlos en mi computador antes de meterme al servidor.

Muchas gracias de antemano!

**Comment by fddelabarra** [comment]
Hola,

El servidor y los test aún no están listos, se avisará en su momento cuando estos sean subidos.

Saludos
