### ISSUE TITLE
Output SPLIT-BATIPLAYLIST

### ISSUE THREAD

**Issue by Madauy** [IIC2133-PUC/2022-2#18]
Hola,
En la parte C punto 3 de SPLIT-BATIPLAYLIST no hay ningún output especificado, no se debe poner nada? o es un error de enunciado?

**Comment by CarloGauss33** [comment]
Hola @Madauy En efecto el evento no tiene output de por si. Si no que se revisa en eventos consecutivos imprimiendo las playlists. 

Exito con tu tarea!
