### ISSUE TITLE
T0: Ids de canciones en comando PLAY-BATIPLAYLIST

### ISSUE THREAD

**Issue by Artaudd** [IIC2133-PUC/2022-2#19]
Hola!, al utilizar el comando PLAY-BATIPLAYLIST y mostrar las canciones de la playlist elegida, ¿las ids de estas deben ser en relación a la playlist o en relación al disco al cual pertenecen? 

Muchas gracias de antemano <3

**Comment by fddelabarra** [comment]
Hola!

Es en relación al disco al que pertenecen.

Saludos!
