### ISSUE TITLE
Manejo de batiplaylists y sus id's

### ISSUE THREAD

**Issue by Agustinuv** [IIC2133-PUC/2022-2#20]
Holaa, para las playlists, estas también serán con id's consecutivos? Pensado en que entonces `CREAR-BATIPLAYLIST playlistID` serán id's desde 0 hasta `P` y no números arbitrarios fuera de este rango.
Aprovecho de preguntar, ¿hay que manejar errores o se asume que si se usa esa acción la playlist `playlistID` estará siempre desocupada y si se elimina una batiplaylist esta sí va a existir? 
Gracias

**Comment by CarloGauss33** [comment]
No, Serán números arbitrarios dado por el input

Puedes asumir que ese espacio estara disponible

**Comment by CarloGauss33** [comment]
Me falto aclarar que si bien no son consecutivos. **Siempre estarán dentro del rango**

**Comment by rbmeza** [comment]
> Me falto aclarar que si bien no son consecutivos. **Siempre estarán dentro del rango**

Respecto a esto, pasa lo mismo en SPLIT-BATIPLAYLIST con el NewPlaylistId? Este siempre estará dentro del rango dado al principio del input.txt?
