### ISSUE TITLE
Input ELIMINAR-CANCION-BATIPLAYLIST

### ISSUE THREAD

**Issue by Mgagol** [IIC2133-PUC/2022-2#21]
Hola
En el enunciado sale que el input de este evento es: playlistID diskID songID. 
Pero en el main solo se solicitan playlistID y songID al hacer fscanf del input file.
¿Deberíamos agregar diskID al fscanf o este no se entregará al llamar a este evento en el input file?

Gracias de antemano 👍

**Comment by fddelabarra** [comment]
Hola,

Esta duda fue respondida en la issue #9 

Saludos
