### ISSUE TITLE
Modificar main.c

### ISSUE THREAD

**Issue by ebenstom** [IIC2133-PUC/2022-2#22]
Hola, estaba leyendo el código main y me pregunto si puedo modificar partes fuera de donde sale COMPLETAR, sino donde y como está puesto la dirección en la que se guardan los discos y playlist?

**Comment by hebusch** [comment]
Hola @ebenstom, puedes modificar lo que quieras del archivo main.c

**Comment by ebenstom** [comment]
gracias!
