### ISSUE TITLE
Incongruencia enunciado con output

### ISSUE THREAD

**Issue by Tsbalart** [IIC2133-PUC/2022-2#23]
Hola revisando el primer test (A_00.txt), me di cuenta que en el evento Imprimir disco, el output es de esta forma:
ESTADO DISCO 15
	23
	0
	6 10
	0 1
	7049
	Canciones
		0
		1
		2
Sin embargo, el 0 en este caso no se que seria, ya que el enunciado solo pide lo siguiente:
ESTADO DISCO diskID
    N SLOTS
    MAX RATING songID
    MIN RATING songID
    TOTAL LENGTH
    CANCIONES
        ID_CANCION 1
        ID_CANCION 2
        ID_CANCION 3

**Comment by fddelabarra** [comment]
Hola!

Gracias por la observación, en la pauta imprimimos

ESTADO DISCO diskID
Capacidad
Slots disponibles
....

Se está arreglando el output correcto, avisaran apenas lo suban

**Comment by CarloGauss33** [comment]
Ahora deberia aparecer todo OK
