### ISSUE TITLE
IMPORTANTE: Tests y Evento IMPRIMIR-DISCO

### ISSUE THREAD

**Issue by CarloGauss33** [IIC2133-PUC/2022-2#24]
Un par de aclaraciones.

1. Primero se actualizaron los tests debido a problemas de formato.

2. N_SLOTS en el evento IMPRIMIR-DISCO hace referencia a la capacidad del disco, no a la cantidad de espacios restantes (Ya que siempre sera 0)

exito con la tarea!

**Comment by v1toco** [comment]
Entonces lo mencionado en https://github.com/IIC2133-PUC/2022-2/issues/23#issuecomment-1221448806 estaría mal no?
