### ISSUE TITLE
Instrucciones

### ISSUE THREAD

**Issue by ebenstom** [IIC2133-PUC/2022-2#25]
Hola, no me queda claro el funcionamiento de command. leyendo los test, cada línea sería un command? Por ejemplo en la instrucción CREAR_DISCO, sale que nos llega capacity, lenght y rating. Nos irían llegando cada línea por separado como sale en el input.txt o se haría un arreglo que tenemos que leer completo con todos los length de canciones ordenados.

**Comment by fddelabarra** [comment]
Hola!

por lo que entiendo, quieres saber cómo funciona el comando ```fscanf```  que va leyendo el archivo input.txt? , ya que no se recibe un array, sino que se leen “por línea o dato”
si es así, en discord explicaron muy bien su funcionamiento, te envío link del mensaje [aquí](https://discord.com/channels/1005259001656770680/1005259002747310094/1010070467652091914)

Espero te ayude, saludos!

**Comment by ebenstom** [comment]
Hola, muchas gracias, ahora entendí como funciona el comando fscanf, pero me surge la duda, entonces de ahora en adelante, por ejemplo, en el mismo comando de CREAR-DISCO, debería yo utilizar esta función para importar por cada canción el length y rating, cierto?

**Comment by fddelabarra** [comment]
eso mismo :)

**Comment by ebenstom** [comment]
ya gracias, es que he estado perdido mucho rato :(

**Comment by fddelabarra** [comment]
aveces pasa :(
Mucho exito en tu tarea!
