### ISSUE TITLE
Duda canciones repetidas al AGREGAR-CANCION-BATIPLAYLIST

### ISSUE THREAD

**Issue by franc1899** [IIC2133-PUC/2022-2#26]
Hola, quería saber si al agregar canciones a una playlist existe la posibilidad de que se pida agregar una canción ya existente en la playlist, en ese caso como deberíamos manejarlo? Ignoramos la canción?

Gracias!

**Comment by fddelabarra** [comment]
Hola!

Efectivamente, si la canción ya fue agregada con anterioridad, solo debes ignorarla para que esta no se repita.

**Comment by ignaciovilla** [comment]
Hola! En ese caso no se imprime nada?
Muchas gracias de antemano.

**Comment by franc1899** [comment]
En mi caso no imprimi nada y tengo los outputs buenos

**Comment by ignaciovilla** [comment]
Buenaa, gracias!
