### ISSUE TITLE
Trabado en la primera parte CREAR DISCOS

### ISSUE THREAD

**Issue by Chumi-sun** [IIC2133-PUC/2022-2#27]
Hola, he estado intentando por varios días hacer la función de crear discos y no puedo. Intento hacer un arreglo por cada disco con un "for", pero no sé como guardarlos luego. Necesito ayuda con eso por favor

**Comment by hebusch** [comment]
Hola @Chumi-sun, te recomiendo utilizar el discord del curso para que te podamos ayudar con esto.
