### ISSUE TITLE
Problema con las pruebas de servidosres

### ISSUE THREAD

**Issue by vicente999** [IIC2133-PUC/2022-2#30]
Holaa tengo un problema cuando intento hacer las pruebas con los servidores, me sale:
Test general:
Repo: TX-2022-2-USERNAME
Branch: master
Repositorio invalido.

y tambien test de evaluacion:
Repo: TX-2022-2-USERNAME
Repositorio invalido.

**Comment by hebusch** [comment]
Hola @vicente999, creo que no estás ingresando el repo correctamente, la idea es remplazar `TX-2022-2-USERNAME` con la información solicitada. En tu caso deberías ingresar el repo `T0-2022-2-vicente999`. Avísame si te funciona.

**Comment by vicente999** [comment]
Eso es lo que no entiendo, el curso me dio la repo de la T0 y la tengo guardada en favoritos. Para que los servidores me funcionen, tengo que clonar esa repo a mi repo personal?

**Comment by hebusch** [comment]
Debes cambiar los parámetros de la URL. En tu caso deberías entrar al siguiente enlace: `http://edd.ing.puc.cl/grade?repo=T0-2022-2-vicente999` para correr los tests de tipo **grade**. 

Como puedes en el parámetro `repo` de la URL es donde debes ingresar el nombre del repositorio de tu tarea.

**Comment by CarloGauss33** [comment]
> Eso es lo que no entiendo, el curso me dio la repo de la T0 y la tengo guardada en favoritos. Para que los servidores me funcionen, tengo que clonar esa repo a mi repo personal?

No, debes utilizar el repositorio que te entregamos. Lo otro importante es que el servidor solo considerara la branch `master`. Y como dice @hebusch tienes que indicar el numero de tarea y tu username para que el servidor sepa la tarea, semestre y alumno asociado a una solicitud.
