### ISSUE TITLE
Resultados test case servidor

### ISSUE THREAD

**Issue by Madauy** [IIC2133-PUC/2022-2#32]
Hola, tengo una duda acerca del resultado del test case.
Estoy utilizando el comando `curl edd.ing.puc.cl/test?repo=T0-2022-2-Madauy` y  para obtener los resultados `curl edd.ing.puc.cl/results?repo=T0-2022-2-Madauy&check=grade`, el primer comando para ejecutar los tests case funciona bien pero al ejecutar el segundo comando me tira lo siguiente:

`[1] 2181`
`Recuerda agregar 'grade' o 'test' al link para lo que desees revisar (edd.ing.puc.cl/repo=<repo>&check=<flag> con <flag> = grade o <flag>=test.)`

Si introduzco **test** solo me dice `[1]+  Done                    curl edd.ing.puc.cl/results?repo=T0-2022-2-Madauy`, deberia decir algo más?
además si pongo **grade** me tira lo mismo pero tambien da el error:

```Command 'grade' not found, did you mean:

  command 'glade' from deb glade (3.22.2-1)
  command 'grace' from deb grace (1:5.1.25-7build1)
  command 'gradle' from deb gradle (4.4.1-10)
  command 'grads' from deb grads (3:2.2.1-2build3)

Try: sudo apt install <deb name>```

**Comment by hebusch** [comment]
Hola @Madauy, a mi me corre correctamente la request cuando antepongo `\` a los símbolos =, ?, &.

`curl edd.ing.puc.cl/results\?repo\=T0-2022-2-Madauy\&check=grade`

Avísame si te funciona.

**Comment by Madauy** [comment]
Ahora si funciona, gracias!
