### ISSUE TITLE
Contenido batiplaylist

### ISSUE THREAD

**Issue by pureyesz** [IIC2133-PUC/2022-2#34]
Hola!

La batiplaylist podría ser una lista enlazada de tipo 

batiplaylist = {{id_cancion_0,id_disco_0},{id_cancion_1,id_disco_1},{id_cancion_2,id_disco_3},{id_cancion_4,id_disco_4},...,{id_cancion_x,id_disco_x}}

por ejemplo:

batiplaylist = {{3,1},{5,1},{0,2},...,{0,1}}

O el contenido de la lista enlazada debe ser estrictamente objetos de canciones? como

batiplaylist = {obj_cancion_0, obj_cancion_1, ...., obj_cancion_x}

**Comment by etoteiza** [comment]
Como tu estimes conveniente
