### ISSUE TITLE
Canciones repetidas en Unir Batiplaylist

### ISSUE THREAD

**Issue by siescobedo** [IIC2133-PUC/2022-2#35]
Hola, quería saber qué se debe hacer en el caso de que una canción de la playlist 2 ya se encuentre en la playlist 1. Agrego toda la playlist 2 al final de la 1 sin importar repeticiones, o debo saltarme las canciones repetidas como es el caso en Agregar-Disco?

**Comment by Baelfire18** [comment]
Se ignoran canciones repetidas

**Comment by siescobedo** [comment]
buena! muchas gracias

**Comment by vblopez** [comment]
Se ignoran significa que no importa que se repitan o que hay que esas no hay que agregarlas?

**Comment by Baelfire18** [comment]
Significa que tienes que saltarte las repetidas si es que encuentras
