### ISSUE TITLE
Tarea 0: Existencia

### ISSUE THREAD

**Issue by vblopez** [IIC2133-PUC/2022-2#36]
Hola!

Debo manejar errores en caso de que se pida manipular algo que no exista? como ignorar la instrucción? o puedo asumir que siempre que me pidan trabajar con algo ya existirá? (por ejemplo si se quiere agregar un disco, este existirá, que si se quiere hacer play, rate, purgar, split de una playlist esta existirá, que al unir ambas playlist existirán..)

Gracias :)

**Comment by tamyhan** [comment]
Hola! 

Puedes asumir que siempre que te pidan manipular algo, ya existirá. 
Las únicas excepciones son en AGREGAR-CANCION-BATIPLAYLIST y ELIMINAR-CANCION-BATIPLAYLIST en donde puede que la canción no exista. En ese caso debes seguir las instrucciones del enunciado.

Saludos!

**Comment by vblopez** [comment]
Gracias!
