### ISSUE TITLE
Tarea 0 y discord

### ISSUE THREAD

**Issue by Icarus328** [IIC2133-PUC/2022-2#37]
Hola, 

Cuando intento correr la tarea 0 para ver si funciona me sale un error "segmentation fault (core dumped)". Cuando lo corro con valgrind me tira error en la linea 48 que venía así diciendo "invalid read of size 4".

Pensé también en pedir ayuda por el discord pero no están los canales de texto a los que se hace alusión en reglas.

**Comment by carolinamaggi** [comment]
Hola, te acabo de dar rol de alumno así puedes ver los canales en discord, en cuanto a tu problema probablemente en la linea 48 estás leyendo mal una variable, específicamente un int.
