### ISSUE TITLE
[Tarea 0] SPLIT-BATIPLAYLIST

### ISSUE THREAD

**Issue by inarrgd** [IIC2133-PUC/2022-2#38]
Hola!
Tengo una duda, desde qué cantidad de canciones se puede asumir que se hará split a una playlist?
Me explico, puede haber una playlist de 1 canción, y hacer split en la posición 0, dejando la playlist 1 vacía y la 2 con la canción 1? y en caso de que no haya canciones en la playlist 1, al hacer split, se crea la playlist 2 vacía, quedando ambas sin caciones? Me serviría bastante si pueden explicar bien los casos borde de esta función.

De antemano muchas gracias, saludos!

**Comment by tamyhan** [comment]
Hola!
Las playlists a las que se hará split siempre tendrán mínimo 2 canciones y nunca se va a pedir que se haga un split en la posición 0. Es decir, después de un split ambas playlists van a quedar con al menos una canción.
