### ISSUE TITLE
Rating y length

### ISSUE THREAD

**Issue by Icarus328** [IIC2133-PUC/2022-2#41]
Hola, 

quiero saber si puedo asumir que valores como rating y length siempre serán positivos, y también me gustaría saber si hay un valor maximo de rating (100, por ejemplo).

Saludos!

**Comment by ShescBlank** [comment]
Hola Icarus, te comparto una captura de pantalla de una respuesta que se dio por discord:
![image](https://user-images.githubusercontent.com/53873288/186659915-b0ba6178-9e9d-4c44-89ad-6645a42ebd81.png)
Saludos y éxito con la tarea!
