### ISSUE TITLE
ELMINAR-BATIPLAYLIST

### ISSUE THREAD

**Issue by cristobal-larach** [IIC2133-PUC/2022-2#42]
Hola, el input parte con el número de batiplaylists a crear (P). Cuando se elimina una batiplaylist (parte c, función 1), ¿existe la posibilidad de que más adelante se cree una nueva playlist para que ocupe su lugar (y volver a tener las P  batyplaylists)? O simplemente se "anula" su referencia?

**Comment by cristobal-larach** [comment]
Otra manera de plantearlo: ¿La suma de la cantidad de comandos "crear batiplaylist" podría ser mayor a P, a partir del uso de "eliminar batiplaylist"?

**Comment by etoteiza** [comment]
Esto está respondido en la issue #20

**Comment by cristobal-larach** [comment]
Hola, la verdad es que no me sirvió mucho esa issue. Lo que quiero saber es si acaso puede aparecer el comando "crear batiplaylist" más de P veces (por ejemplo, si p = 10, crear 10 playlists, eliminar una playlist, y luego crear otra para ocupar el lugar de la eliminada)

**Comment by etoteiza** [comment]
Sí, puede pasar eso. Considera que nunca se superará la cantidad P de playlist que va a tener el programa

**Comment by etoteiza** [comment]
Recuerda también que las batiplaylist no sólo se crean con el evento `CREAR-BATIPLAYLIST`, sino que también puede ser con `SPLIT-BATIPLAYLIST` , pero siempre estarán dentro de la cantidad arbitraria P
