### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by vicente999** [IIC2133-PUC/2022-2#43]
Holaa tengo una duda, que hago los testcases del servidor general y estan todos corrector, pero luego al ejecutar los test de evaluación estan todos malos ('wrong output'). No se que hacer jajajajaj

**Comment by etoteiza** [comment]
No entiendo que quieres decir, estás utilizando los tests locales más actualizados del drive?

**Comment by vicente999** [comment]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/53841116/186744066-1c95af5a-8e60-4f96-a0b1-65a5c307287a.png">
<img width="499" alt="image" src="https://user-images.githubusercontent.com/53841116/186744288-5ad15798-2ec8-45b7-85ab-87aad0f175d4.png">

**Comment by etoteiza** [comment]
Los test de grade son distintos a los del tests. Ejecutalo de nuevo y si te sigue saliendo el mismo problema, recomiendo revisar tu output utilizando los tests que están en el drive
