### ISSUE TITLE
ELIMINAR-CANCION-BATIPLAYLIST

### ISSUE THREAD

**Issue by JZapataMA** [IIC2133-PUC/2022-2#44]
Hola, me di cuenta que en el enunciado se nos menciona este apartado tal que:

ELIMINAR-CANCION-BATIPLAYLIST playlistID diskID songID

sin embargo, en el main los inputs que el la función recibe no incluye el diskID, hay problema con agregarlo o hay un error ahí?

GRACIASSSSSSSSSS

**Comment by etoteiza** [comment]
Eso debes modificarlo tu para que reciba ese valor
