### ISSUE TITLE
Diff enunciado y tests

### ISSUE THREAD

**Issue by 0wulf** [IIC2133-PUC/2022-2#49]
Hola buenas,

Estoy teniendo problemas para obtener el _output_ correcto en los tests C nivel medium y hard.
Analizando mi _output_ y la solución entregada por el equipo de ayudantes, me percaté de que 
mi código no revisa si cada canción a agregar se encuentra previamente en una playlist a la hora de 
procesar instrucciones tipo UNIR, lo que aparentemente sí realiza el código con el que se generó 
los tests. Este comportamiento (el que no se agreguen canciones que ya están) no está especificado 
en el enunciado para el caso de la instrucción UNIR, sino que solo aparece para la instrucción AGREGAR-DISCO.
De igual manera, es probable que esté teniendo el mismo problema con la instrucción AGREGAR-CANCION-BATIPLAYLIST
pues tampoco se especifica tal comportamiento.

Por ejemplo:
medium/solutions/C_01.txt
La playlist 85 sufre JOIN con playlist 116 (línea 34502 del output entregado). Esta última contiene canciones del disco 114 que ya se encuentran en 85.
Luego del JOIN se utiliza PLAY (34984) a lo que mi _output_ imprime tales canciones repetidas mientras que el _output_ entregado excluye tales canciones. 

En resumen, me gustaría saber si mi teoría de que se filtraron canciones en JOIN para los tests entregados es correcta
y si requeriré de implementar tal comportamiento.

**Comment by fddelabarra** [comment]
Hola!,
Efectivamente, esto fue respondido en las peguntas de discord, debes revisar si la canción ya existe en la batiplaylist o no, y si ya existe debes ignorarla y no añadirla.

Espero te haya servido!, saludos!

**Comment by 0wulf** [comment]
Muchas gracias por la respuesta, no había leido tal issue.
