### ISSUE TITLE
Duda AGREGAR-CANCION-BATIPLAYLIST, playlist que no existe

### ISSUE THREAD

**Issue by gustavoselman** [IIC2133-PUC/2022-2#51]
Hola, hasta ahora he supuesto, que jamás me pedirán que **agregue una canción** a una **playlist que no existe**.

¿Este supuesto es correcto?

**Comment by ShescBlank** [comment]
Sip, ese supuesto es correcto. En el servidor de Discord hay un canal de texto con las dudas frecuentes de la tarea, ahí hay harta información sobre los supuestos que pueden hacer.
Éxito con la tarea!

**Comment by gustavoselman** [comment]
Gracias!

**Comment by matiasghf** [comment]
Entonces podriamos suponer también que el disk ID de esa misma instrucción también existe?

**Comment by ShescBlank** [comment]
Los discos no se pueden eliminar, así que sí

**Comment by Araos827** [comment]
Hola, probando en el test C01 hard si me aparece este caso borde, por si alguien me puede confirmar :)
