### ISSUE TITLE
Usuario inexistente en Servidor

### ISSUE THREAD

**Issue by isidonoso** [IIC2133-PUC/2022-2#53]
Holaa, estoy intentando ocupar el servidor pero me sale lo siguiente:
![image](https://user-images.githubusercontent.com/48329201/187213681-c54c275f-d068-4b4e-a83e-1cec871fdda7.png)
Por qué puede ser? El link al que estoy ingresando es: http://edd.ing.puc.cl/test?repo=T0-2022-2-isidonoso

Graciaas!

**Comment by CarloGauss33** [comment]
Hola @isidonoso, Enviame correo a cparedesr@uc.cl con tu rut, mail y usuario de github. Probablemente quedo mal registrado tu usuario en el formulario
