### ISSUE TITLE
PURGAR-BATIPLAYLIST

### ISSUE THREAD

**Issue by crisfernandezj** [IIC2133-PUC/2022-2#54]
Hola! En esta pregunta rating siempre es int, o puede ser float?

**Comment by ShescBlank** [comment]
Int

**Comment by crisfernandezj** [comment]
Ya perfecto. Eso si en los tests de medium algunas veces ponían el rating como float en el valor de entrada. Por ejemplo en C_00.txt una instrucción es: PURGAR-BATIPLAYLIST 170 2.5.

Eso está mal entonces verdad?

**Comment by ShescBlank** [comment]
Sip, debes leerlos como ints #47
