### ISSUE TITLE
Agregar canción repetida

### ISSUE THREAD

**Issue by ivigiglio** [IIC2133-PUC/2022-2#56]
Hola! quería saber si se agrega una canción que ya está en la lista, debemos agregarla de todas maneras o no la agregamos? ya que en agregar disco se dice que no se agreguen repetidas, pero en agregar canción no se pide eso.

**Comment by ShescBlank** [comment]
Hola, te mando un pantallazo del canal de discord de dudas frecuentes de la tarea 0
![Screenshot_20220829-154559_Discord](https://user-images.githubusercontent.com/53873288/187285470-87b5d696-340c-4b11-880e-326c116a50e8.jpg)

**Comment by matiasghf** [comment]
Entonces en teoría los repetidos en la playlist pueden venir sólo de agregar un disco o unir 2 playlist o no?

**Comment by ShescBlank** [comment]
Sip
