### ISSUE TITLE
Dudas varias acerca de suposisiones e output de PLAY-BATIPLAYLIST

### ISSUE THREAD

**Issue by Icarus328** [IIC2133-PUC/2022-2#58]
Hola,
Tengo algunas dudas sobre cosas que puedo suponer, y algo que no me queda claro del output.

1) puedo asumir que toda operación de playlists se hara sobre playlists que existen? (Ej: no eliminar canciones de playlist que no existen, no eliminar una playlist que no existe, etc)

2)Puedo asumir que no me pediran crear 2 veces una playlist con la misma id, aún si se elimina la anterior? (Es decir, si creo una playlist con id 0, no me pediran que vuelva  a crear otra playlist con id 0, aún si elimino la original)

3)Puedo asumir que en B.4 no me pediran agregar un disco que no existe?

4)En B.5 PLAY-BATIPLAYLIST el formato después de canciones es

ID_CANCION 1 diskID
ID_CANCION 2 diskID
ID_CANCION 3 diskID

pero en los tests solo hay dos campos que no me queda muy claro que representan, son ID_CANCION y diskID? entonces el output real de esa parte seria algo más como

ID_CANCION diskID

?

Gracias!

**Comment by ShescBlank** [comment]
Hola
1) es de las primeras dudas frecuentes del canal de preguntas frecuentes del Discord, pero sip, puedes asumir que las operaciones sobre playlists son válidas.
2) No te lo puedo asegurar tu programa debería poder manejarlo
3) el disco existirá, recuerda que no se pueden elminar discos
4) entiendo que causa dudas pero sip, la enumeración del enunciado es solo para que se escriban los ids de canciones en el orden que van llegando. Para dudas de este estilo siempre puedes guiarte por el output que les damos
