### ISSUE TITLE
Archivos input.txt 

### ISSUE THREAD

**Issue by Fernan-tess** [IIC2133-PUC/2022-2#6]
Hola,

¿Dónde puedo encontrar archivos input.txt con su respectivo output.txt esperado? Para la tarea 0

Gracias

**Comment by fddelabarra** [comment]
Los archivos input.txt y output.txt son archivos test, los cuales serán subidos más adelante.

Mientras tanto puedes crear un pequeño test de ejemplo para ir probando cómo está funcionando tu programa.

Y sobre el archivo output.txt, este corresponde al output creado por el programa, por lo que el archivo puede tener cualquier nombre.

**Comment by josefinacortes** [comment]
Hola! 
Respecto a esto, será posible que suban algunos mini ejemplos antes? Creo que hay algunas cosas que no quedan muy claras sin esos (Por ejemplo los songId ¿Nosotros los definimos?, que hacer al eliminar una canción, Si el total length es de todas las canciones iniciales o debe actualizarse, entre otras cosas).
Muchas gracias de antemano!

**Comment by FGarciaVarela** [comment]
Hola! Tuve la misma duda pero cuando lo ejecuto en el paso final me tira el error de "segmentation fault". (Lo ejecuto desde Ubuntu). Intenté algunas cosas pero me sigue arrojando el mismo error, y no sé si hay algún tip para solucionarlo?
De antemano muchas gracias!

**Comment by fddelabarra** [comment]
Ya intentaste debuggear para encontrar el error?

**Comment by Baelfire18** [comment]
@FGarciaVarela eso es porque tu código falla en algo. Puedes intentar debuggear usando:

valgrind ./dccomics input.txt output.txt

**Comment by FGarciaVarela** [comment]
@Baelfire18 Acabo de hacerlo pero sigue tirandome el error "Segmentation fault". Estoy intentando con el archivo base (sin modificaciones).

**Comment by Baelfire18** [comment]
@FGarciaVarela puedes discord en la tarde para revisarlo?

**Comment by ftocornal** [comment]
Hola,
Tengo el mismo problema, como se soluciona?
gracias

**Comment by FGarciaVarela** [comment]
Hola! Al final la solución (o al menos lo que me sirvió) fue dejar el archivo input.txt en donde está el makefile, gitignore, etc, y no en donde está el main y los demás archivos.

Saludos!

**Comment by ftocornal** [comment]
Ok gracias!
