### ISSUE TITLE
SPLIT BATIPLAYLIST

### ISSUE THREAD

**Issue by Icarus328** [IIC2133-PUC/2022-2#61]
Hola, tengo una duda de como se considera la posicion en split batiplaylist, ya que las issues #38 y #28 se contradicen entre sí.

De la misma manera, si me dan una posición 1, es partiendo desde el 0? (Es decir, la cancion en la posición 1 es la segunda canción de la playlist?)

Gracias!

**Comment by fddelabarra** [comment]
No se contradicen, se refiere a que la posición parte de 0 (al contar) y la otra issue menciona que en una batiplaylist siempre habrá al menos 2 canciones, de esta manera al hacer split siempre quedarán 2 batiplaylist con la menos 1 canción cada una, o sea no quedará una vacia
