### ISSUE TITLE
Archivo main para la parte 2

### ISSUE THREAD

**Issue by AlonsoZamorano** [IIC2133-PUC/2022-2#62]
En la tarea falta el archivo 'main.c' para la parte 2 o lo tenemos que crear desde 0 nosotros?

**Comment by CarloGauss33** [comment]
A que te refieres?. Lo veo en todos los repositorios (Dentro de la carpeta bstman)

**Comment by AlonsoZamorano** [comment]
Ahhhh yaya perdon no habia visto bien. Muchas graciasss
