### ISSUE TITLE
Tarea 0:  Ids

### ISSUE THREAD

**Issue by vblopez** [IIC2133-PUC/2022-2#7]
Hola!

No me queda claro que id´s utilizar, tanto de las entidades primarias -por así decirlo- como de las entidades en las que se especifica que es un id relativo. Dado que los ids se ocupan en los archivos de input, y que se tendran outputs predeterminados, es que asumo que estos no son arbitrarios y por ende es importante ocupar los ids correctos.

Gracias :)

**Comment by hebusch** [comment]
Hola @vblopez!

Los id's los tienes que asignar tú de manera creciente en orden de "llegada".

**Comment by ElTioAndresCabezas** [comment]
Con esto, se refieren a que los discos deben tener ID 0, 1, 2... donde el disco con ID 0 es el primer disco creado?
También, los IDs asumimos que parten desde 0 o desde 1?

**Comment by hebusch** [comment]
@ElTioAndresCabezas 
> Con esto, se refieren a que los discos deben tener ID 0, 1, 2... donde el disco con ID 0 es el primer disco creado?

Si

> También, los IDs asumimos que parten desde 0 o desde 1?

Todos los ID's parten desde 0.

**Comment by ElTioAndresCabezas** [comment]
Gracias!

**Comment by pabloalvarez67** [comment]
Los IDS de las canciones varían en cada disco? por ejemplo el disco 0 tiene canciones con id (0,1,...n). Y el disco 1 también tiene canciones con id (0,1,...n)? 
O los IDS de canciones son independientes a cada disco sin que se repitan?

**Comment by pabloalvarez67** [comment]
> @hebusch  Los IDS de las canciones varían en cada disco? por ejemplo el disco 0 tiene canciones con id (0,1,...n). Y el disco 1 también tiene canciones con id (0,1,...n)? O los IDS de canciones son independientes a cada disco sin que se repitan?

**Comment by hebusch** [comment]
@pabloalvarez67 los ID's de las canciones son relativos a su disco. Es decir, cada disco tendrá canciones con id 0,1,2...
