### ISSUE TITLE
Tarea 0: input de length, rating

### ISSUE THREAD

**Issue by IgnAMS** [IIC2133-PUC/2022-2#8]
Hola, estaba leyendo el código proporcionado, en específico en la parte de "Crear Disco", donde venía declarado el `length` y el `rating` como `int's`. Ante esto me surgió la duda si el input lo tenemos que leer nosotros o si debería venir en el código, dado que en otras variables como `capacity`, `disk_id`, etc,  ya vienen con su lectura en el código proporcionado. Además en Rate Batiplaylist se menciona que el `rating` puede ser decimal, en ese caso se debería ¿cambiar el código proporcionado?

**Comment by fddelabarra** [comment]
El input en Crear Disco, N corresponde a la cantidad de canciones que contendrá el disco (o ```capacity``` de disco), luego se procede a entregar N lineas (N canciones) con su respectivo ```length``` y  ```rating``` (que serán int), los cuales estarán en ``ìnput.txt```, el codigo proporcionado solo inicializa las variables a utilizar, tu debes crear el código que se encargue de leer estos datos.
Sobre Rate Batiplaylist, cuando se menciona que ```rating```puede ser un decimal es porque este corresponde el promedio pedido (como indica el enunciado).
