### ISSUE TITLE
[ T0 ] ELIMINAR-CANCION-BATIPLAYLIST

### ISSUE THREAD

**Issue by jtconcha** [IIC2133-PUC/2022-2#9]
hola! en el enunciado sale que la función recibe como argumentos playlistID, diskID y songID, pero en el archivo main.c solo aparece que recibe playlist_id y song_id. ¿Por cuál de los dos me debería guiar? gracias de antemano!

**Comment by hebusch** [comment]
Hola @jtconcha!

Debes guiarte por el enunciado. Saludos :smile:
