### ISSUE TITLE
T2 Error raro de output (caracter invisible ^M faltante)

### ISSUE THREAD

**Issue by diegotmz** [IIC2133-PUC/2022-2#96]
Hola! Tengo una duda, cuando corro mi programa mi output es exactamente igual al esperado de las soluciones, e incluso la funcion check_output me da score de 100%, al correr diff me tira diferencia en todas las lineas pero no me muestra ninguna diferencia. Al correr este comando con | cat -t me muestra los caracteres invisibles y me dice que en todas las lineas me falta un ^M en el output. Pensé que era un error de memoria que tenía del tipo conditional jump, pero lo arreglé y sigo teniendo este problema, por lo que en el servidor tengo puros WRONG OUTPUT. Alguno sabe porque podria ser? No he tocado el Makefile ni nada. :/

**Comment by carolinamaggi** [comment]
Comparaste tu output solo con las demo? o también los del drive? porque las demo son muy chicos para tener test así en el server

**Comment by diegotmz** [comment]
@carolinamaggi Sí, tengo todos los del drive con score 100% con la funcion check_output.py pero en el diff me tira diferencias en todas las lineas con el mismo error de antes con ese caracter invisible, y en el servidor tmbn tengo full WRONG OUTPUT.

**Comment by diegotmz** [comment]
Alfinal al parecer era algún error de memoria raro que me causaba eso, pero lo arreglé y desaparecieron :).
